(()=>{'use strict';
  const SUPABASE_URL='https://pbzukefsrtmymowlsdrp.supabase.co';
  const PUBLISHABLE_KEY='sb_publishable_fIWTEv4S7qnetQuMbyxQjA_3KffY1lf';
  const LOGIN_DOMAIN='admin.afrroleplay-apv.nl',SESSION_KEY='afr-admin-session';
  const $=s=>document.querySelector(s),overlay=$('#adminOverlay'),loginView=$('#adminLogin'),dashboard=$('#adminDashboard'),quickLinks=$('.admin-quick-links'),adminOpen=$('.admin-open');
  let session=null,profile=null,accounts=[];

  function status(el,message,type=''){el.textContent=message;el.className='admin-status'+(type?' '+type:'')}
  async function parseResponse(response){const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch(e){data=text}if(!response.ok){const message=data?.msg||data?.message||data?.error_description||data?.error||'Er ging iets mis.';throw new Error(message)}return data}
  async function publicRequest(path,options={}){return parseResponse(await fetch(SUPABASE_URL+path,{...options,headers:{apikey:PUBLISHABLE_KEY,'Content-Type':'application/json',...(options.headers||{})}}))}
  async function authRequest(path,options={}){if(!session?.access_token)throw new Error('Log opnieuw in.');return parseResponse(await fetch(SUPABASE_URL+path,{...options,headers:{apikey:PUBLISHABLE_KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json',...(options.headers||{})}}))}
  function saveSession(value){session=value;try{value?localStorage.setItem(SESSION_KEY,JSON.stringify(value)):localStorage.removeItem(SESSION_KEY)}catch(e){}}
  function storedSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch(e){return null}}
  async function refreshSession(){if(!session?.refresh_token)throw new Error('Sessie verlopen.');const next=await publicRequest('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});next.expires_at=Math.floor(Date.now()/1000)+next.expires_in;saveSession(next)}
  async function ensureSession(){if(session?.expires_at&&session.expires_at<Math.floor(Date.now()/1000)+60)await refreshSession()}
  async function loadProfile(){await ensureSession();const rows=await authRequest('/rest/v1/admin_profiles?id=eq.'+encodeURIComponent(session.user.id)+'&select=*');const item=rows?.[0];if(!item||!item.active)throw new Error('Dit account heeft geen actieve beheerdersrechten.');profile=item;return item}
  const can=permission=>profile?.role==='owner'||profile?.permissions?.includes(permission);

  function openPanel(){overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>$('#adminUsername')?.focus(),80)}
  function closePanel(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');document.body.style.overflow=''}
  adminOpen.addEventListener('click',()=>{if(profile){selectAdminTab('overview');openPanel()}else openPanel()});$('.admin-close').addEventListener('click',closePanel);overlay.addEventListener('click',e=>{if(e.target===overlay)closePanel()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&overlay.classList.contains('open'))closePanel()});

  function showDashboard(){loginView.hidden=true;dashboard.hidden=false;document.body.classList.add('admin-authenticated');quickLinks.hidden=false;adminOpen.querySelector('span:last-child').textContent=profile.display_name;$('#adminDisplayName').textContent=profile.display_name;$('#adminRole').textContent=profile.role;$('#adminRoleStat').textContent=profile.role;document.querySelectorAll('.admin-tab,[data-open-admin]').forEach(button=>{const tab=button.dataset.adminTab||button.dataset.openAdmin;button.hidden=(tab==='accounts'&&!can('manage_accounts'))||(tab==='audit'&&!can('view_audit_log'))||(tab==='articles'&&!can('manage_articles'))||(tab==='maintenance'&&!can('manage_maintenance'))});loadOverview()}
  function showLogin(){dashboard.hidden=true;loginView.hidden=false;profile=null;accounts=[];document.body.classList.remove('admin-authenticated');quickLinks.hidden=true;adminOpen.querySelector('span:last-child').textContent='Beheer'}
  $('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter,username=$('#adminUsername').value.trim().toLowerCase(),password=$('#adminPassword').value;status($('#adminLoginStatus'),'Beveiligd controleren…');button.disabled=true;try{if(!/^[a-z0-9._-]{3,32}$/.test(username))throw new Error('Controleer de gebruikersnaam.');const data=await publicRequest('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:username+'@'+LOGIN_DOMAIN,password})});data.expires_at=Math.floor(Date.now()/1000)+data.expires_in;saveSession(data);await loadProfile();$('#adminPassword').value='';showDashboard();closePanel();status($('#adminLoginStatus'),'')}catch(err){saveSession(null);status($('#adminLoginStatus'),err.message,'error')}finally{button.disabled=false}});
  async function logoutAdmin(){try{if(session)await authRequest('/auth/v1/logout',{method:'POST'})}catch(e){}saveSession(null);showLogin();closePanel()}
  $('#adminLogout').addEventListener('click',logoutAdmin);$('#adminQuickLogout').addEventListener('click',logoutAdmin);

  function selectAdminTab(tab){document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x.dataset.adminTab===tab));document.querySelectorAll('.admin-view').forEach(view=>view.classList.toggle('active',view.dataset.adminView===tab));if(tab==='articles')loadArticlePublisher();if(tab==='maintenance')loadMaintenanceForm();if(tab==='accounts')loadAccounts();if(tab==='audit')loadAudit();if(tab==='overview')loadOverview()}
  document.querySelectorAll('.admin-tab').forEach(button=>button.addEventListener('click',()=>selectAdminTab(button.dataset.adminTab)));
  document.querySelectorAll('[data-open-admin]').forEach(button=>button.addEventListener('click',()=>{selectAdminTab(button.dataset.openAdmin);openPanel()}));

  async function loadOverview(){try{accounts=await authRequest('/rest/v1/admin_profiles?select=id,active');$('#adminAccountCount').textContent=accounts.length;$('#adminActiveCount').textContent=accounts.filter(x=>x.active).length}catch(e){$('#adminAccountCount').textContent='—';$('#adminActiveCount').textContent='—'}}

  function renderArticlePreview(){const title=$('#articleTitle').value.trim(),content=$('#articleContent').value.trim(),category=$('#articleCategory').value;$('#articlePreviewTitle').textContent=title||'Jouw artikeltitel';$('#articlePreviewContent').textContent=content||'De artikeltekst verschijnt hier terwijl je typt.';$('#articlePreviewCategory').textContent=category;$('#articlePreviewCategory').hidden=!category}
  ['#articleTitle','#articleContent','#articleCategory'].forEach(selector=>$(selector).addEventListener('input',renderArticlePreview));
  async function loadRecentPublished(){const box=$('#recentPublishedList');if(!can('view_audit_log')){box.textContent='Alleen zichtbaar met activiteitenrechten.';return}try{const rows=await authRequest('/rest/v1/admin_audit_log?action=eq.article_created&select=id,target,details,created_at&order=created_at.desc&limit=8');box.textContent='';rows.forEach(item=>{const row=document.createElement('div');row.className='recent-published-item';const title=document.createElement('strong'),meta=document.createElement('small');title.textContent=item.details?.title||'Artikel';meta.textContent=(item.details?.page||item.target||'')+' · '+new Date(item.created_at).toLocaleString('nl-NL');row.append(title,meta);box.append(row)});if(!rows.length)box.textContent='Nog geen artikelen gepubliceerd.'}catch(e){box.textContent='Publicatiegeschiedenis kon niet worden geladen.'}}
  function loadArticlePublisher(){renderArticlePreview();loadRecentPublished()}
  $('#articlePublishForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter,el=$('#articlePublishStatus');status(el,'Artikel wordt veilig naar GitHub gestuurd…');button.disabled=true;try{await ensureSession();const payload={page:$('#articlePage').value,title:$('#articleTitle').value.trim(),content:$('#articleContent').value.trim(),category:$('#articleCategory').value};const response=await fetch(SUPABASE_URL+'/functions/v1/admin-publish-article',{method:'POST',headers:{apikey:PUBLISHABLE_KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await parseResponse(response);const selectedPage=$('#articlePage').value;e.target.reset();$('#articlePage').value=selectedPage;renderArticlePreview();status(el,(result?.message||'Artikel gepubliceerd.')+' De site wordt binnen enkele minuten bijgewerkt.','success');loadRecentPublished()}catch(err){status(el,err.message,'error')}finally{button.disabled=false}});

  async function getMaintenance(){const rows=await publicRequest('/rest/v1/site_settings?key=eq.maintenance&select=value');return rows?.[0]?.value||null}
  async function applyMaintenance(){const banner=$('.maintenance-banner');if(!banner)return;try{const cfg=await getMaintenance();if(!cfg)throw new Error();banner.dataset.noticeId=cfg.notice_id||'maintenance';banner.dataset.tone=cfg.tone||'warning';banner.querySelector('.maintenance-copy strong').textContent=cfg.title||'Onderhoud';banner.querySelector('.maintenance-copy span').textContent=cfg.message||'';let dismissed=false;try{dismissed=sessionStorage.getItem('afr-dismissed-maintenance')===banner.dataset.noticeId}catch(e){}banner.classList.toggle('is-hidden',!cfg.enabled||dismissed);banner.classList.add('admin-configured')}catch(e){banner.classList.add('admin-configured')}}
  async function loadMaintenanceForm(){try{const cfg=await getMaintenance();$('#maintenanceEnabled').checked=!!cfg?.enabled;$('#maintenanceTitle').value=cfg?.title||'';$('#maintenanceMessage').value=cfg?.message||'';$('#maintenanceTone').value=cfg?.tone||'warning';status($('#maintenanceStatus'),'')}catch(e){status($('#maintenanceStatus'),e.message,'error')}}
  $('#maintenanceForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;status($('#maintenanceStatus'),'Opslaan…');button.disabled=true;try{const value={enabled:$('#maintenanceEnabled').checked,title:$('#maintenanceTitle').value.trim(),message:$('#maintenanceMessage').value.trim(),tone:$('#maintenanceTone').value,notice_id:'notice-'+Date.now()};await ensureSession();await authRequest('/rest/v1/site_settings?key=eq.maintenance',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({value,updated_by:session.user.id})});status($('#maintenanceStatus'),'Onderhoudsmelding opgeslagen.','success');await applyMaintenance()}catch(err){status($('#maintenanceStatus'),err.message,'error')}finally{button.disabled=false}});

  function accountNode(item){const row=document.createElement('article');row.className='admin-account';const dot=document.createElement('span');dot.className='account-state'+(item.active?' active':'');const copy=document.createElement('div'),name=document.createElement('strong'),user=document.createElement('small'),role=document.createElement('span');name.textContent=item.display_name;user.textContent='@'+item.username;role.className='account-role';role.textContent=item.role;copy.append(name,user);row.append(dot,copy,role);return row}
  async function loadAccounts(){const box=$('#adminAccountsList');box.textContent='Accounts laden…';try{accounts=await authRequest('/rest/v1/admin_profiles?select=id,username,display_name,role,permissions,active,created_at&order=created_at.asc');box.textContent='';accounts.forEach(item=>box.append(accountNode(item)));if(!accounts.length)box.textContent='Geen accounts gevonden.'}catch(e){box.textContent=e.message}}
  $('#createAccountForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter,el=$('#createAccountStatus');status(el,'Account veilig aanmaken…');button.disabled=true;try{await ensureSession();const permissions=[...document.querySelectorAll('input[name="permission"]:checked')].map(x=>x.value);const response=await fetch(SUPABASE_URL+'/functions/v1/admin-create-user',{method:'POST',headers:{apikey:PUBLISHABLE_KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({username:$('#newUsername').value.trim().toLowerCase(),display_name:$('#newDisplayName').value.trim(),password:$('#newPassword').value,role:$('#newRole').value,permissions})});await parseResponse(response);e.target.reset();status(el,'Account is aangemaakt.','success');loadAccounts();loadOverview()}catch(err){const message=/Failed to fetch|404|FunctionsFetchError/i.test(err.message)?'De beveiligde accountfunctie moet nog worden geïnstalleerd.':err.message;status(el,message,'error')}finally{button.disabled=false}});

  async function loadAudit(){const box=$('#adminAuditList');box.textContent='Activiteiten laden…';try{const rows=await authRequest('/rest/v1/admin_audit_log?select=id,action,target,created_at,user_id&order=created_at.desc&limit=40');box.textContent='';rows.forEach(item=>{const row=document.createElement('article');row.className='admin-audit-item';const copy=document.createElement('div'),title=document.createElement('strong'),date=document.createElement('small');title.textContent=item.action+(item.target?' · '+item.target:'');date.textContent=new Date(item.created_at).toLocaleString('nl-NL');copy.append(title,date);row.append(copy);box.append(row)});if(!rows.length)box.textContent='Nog geen activiteiten.'}catch(e){box.textContent=e.message}}

  async function resume(){session=storedSession();if(session){try{await loadProfile();showDashboard()}catch(e){saveSession(null);showLogin()}}applyMaintenance()}
  resume();setInterval(applyMaintenance,5*60*1000);
})();